# Generated by Django 4.0.6 on 2022-07-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='cards.cards'),
        ),
    ]
