# Generated by Django 4.0.6 on 2022-09-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_comment_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='likes',
            new_name='like',
        ),
    ]
