# Generated by Django 4.0.6 on 2022-09-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_likes_cards_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='like',
        ),
    ]
